# Datos de entrenamiento
data:
  train_file: data/train/arabica_train.csv
  target_column: Calidad

# Guardado del modelo entrenado
output_file: models/modelo_final.pkl

# Configuración del modelo
# MERAMENTE INFORMATIVO, NO TOCAR
model:
  pipeline:
    steps:
      - name: selectkbest
        class: SelectKBest
        params:
          k: 9
      - name: pca
        class: PCA
        params:
          n_components: 9
      - name: classifier
        class: GradientBoostingClassifier
        params:
          max_depth: 7
          max_features: 2